name: Conformity-Template-Scanner-GitHubAction

on: 
  push:
    paths: 
      - actionstest.yaml

jobs:      
  CloudFormation-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cloud One Conformity Pipeline Scanner
      uses: raphabot/conformity-template-scanner-pipeline@v1.0.0
      env:
        cc_apikey: ${{ secrets.apikey }}
        maxExtreme: 0
        maxVeryHigh: 0
        maxHigh: 5
        maxMedium: 10
        maxLow: 10
        cc_region: ap-southeast-2
        templatePath: actionstest.yaml
